services:
  mongodb:
    image: mongo:7.0
    container_name: spicy-music-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: spicy_music
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - spicy-music-network

  app:
    build: .
    container_name: spicy-music-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/spicy_music?authSource=admin
      PORT: 3000
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - spicy-music-network
    command: npm run dev

volumes:
  mongodb_data:

networks:
  spicy-music-network:
    driver: bridge
